name: Build

on:
    push:
        branches:
            - master
    pull_request: ~

jobs:
    phpstan:
        runs-on: ubuntu-24.04
        name: PHPStan
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: PHPStan
              uses: docker://oskarstark/phpstan-ga
              env:
                  REQUIRE_DEV: true
              with:
                  args: analyse
    cs-fixer:
        runs-on: ubuntu-24.04
        name: PHP-CS-Fixer
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Fix CS
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                args: --diff --dry-run
    tests:
        runs-on: ubuntu-24.04
        strategy:
            matrix:
                php:
                    - '8.2'
                    - '8.3'
                    - '8.4'
                include:
                    - description: 'Lowest'
                      php: '8.2'
                      composer_option: '--prefer-lowest'
                    - description: 'Symfony 6.4'
                      php: '8.2'
                      symfony: 6.4.*
                    - description: 'Symfony 7.3'
                      php: '8.3'
                      symfony: 7.3.*
                    - description: 'Symfony 7.4'
                      php: '8.4'
                      symfony: 7.4.*@dev
        name: PHP ${{ matrix.php }} tests (${{ matrix.description }})
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: flex
            - name: Setup flex
              run: |
                  composer global config --no-plugins allow-plugins.symfony/flex true
                  composer global require --no-interaction --no-progress symfony/flex:^2.7
                  composer config extra.symfony.require ${{ matrix.symfony }}
            - name: Allow dev dependencies
              run: composer config minimum-stability dev && composer config prefer-stable true
              if: contains(matrix.symfony, '@dev')
            - name: Install dependencies
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependencies }}
              env:
                  SYMFONY_REQUIRE: ${{ matrix.symfony }}
            - name: Run tests
              run: vendor/bin/phpunit --colors=always

